#!/bin/sh

# OS wrapper for POSIX systems that support sudo.  This is a simple
# shell script that will invoke the java oswrapper command with the
# appropriate data.

CLASSPATH=$1
shift
MAIN=$1
shift

# We ignore the classpath and main specified; these are for debugging
# only and cannot be used on a real system as this would allow for
# fairly obvious privilege escalation attacks

exec java -cp '/usr/share/floodlight/java/*' org.projectfloodlight.os.OSConfigWrapper "$@"
