package net.bigdb.auth.session;



/**
 * Interface contract for mapping session cookies to session ids in the
 * REST API.
 * <p>
 *
 * A sessionCookie is an opaque, unpredictable string. Session Cookies generated by the
 * sessionCookieManager are expected to be urlsafe strings of length 512 chars or less.
 * <p>
 * <b>NOTE:</b>SessionCookieManger implementations are required to be thread-safe.
 *
 * @author Andreas Wundsam <andreas.wundsam@bigswitch.com>
 */
public interface SessionCookieManager {
    /**
     * create a session cookie for the given session id, and persist it in the
     * SessionCookieManager.
     *
     * @param sessionData
     * @return the session cookies - urlsafe string <= 512 chars
     */
    String createSessionCookie(Long sessionId);

    /**
     * return the session id associated with the given session cookie.
     *
     * @param cookie
     * @return null if no active session is found
     */
    Long getSessionIdForCookie(String cookie);

    /**
     * remove the session cookie mapping for the given session id. NOOP if no such
     * session exists.
     *
     * @param cookie
     * @return true if a session cookie mapping existed and was removed, false otherwise
     */
    boolean removeSessionForCookie(String cookie);
}
