#!/bin/sh -e

NAME=admin
GROUP=admusrs

remove() {
    if [ -x /usr/sbin/remove-shell ]; then
        remove-shell /usr/bin/floodlight-firstboot
    fi
}

case "$1" in
    purge)
        remove
        deluser --quiet $NAME || true
        delgroup --quiet $GROUP || true
    ;;

    remove|disappear)
        remove
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
