/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.projectfloodlight.sync.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"all", "unchecked", "rawtypes"}) public class LeaderCandMessage implements org.apache.thrift.TBase<LeaderCandMessage, LeaderCandMessage._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LeaderCandMessage");

  private static final org.apache.thrift.protocol.TField HEADER_FIELD_DESC = new org.apache.thrift.protocol.TField("header", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField DOMAIN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("domainId", org.apache.thrift.protocol.TType.I16, (short)2);
  private static final org.apache.thrift.protocol.TField CAND_NODE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("candNodeId", org.apache.thrift.protocol.TType.I16, (short)3);
  private static final org.apache.thrift.protocol.TField CAND_WEIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("candWeight", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new LeaderCandMessageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new LeaderCandMessageTupleSchemeFactory());
  }

  public AsyncMessageHeader header; // required
  public short domainId; // optional
  public short candNodeId; // optional
  public int candWeight; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HEADER((short)1, "header"),
    DOMAIN_ID((short)2, "domainId"),
    CAND_NODE_ID((short)3, "candNodeId"),
    CAND_WEIGHT((short)4, "candWeight");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HEADER
          return HEADER;
        case 2: // DOMAIN_ID
          return DOMAIN_ID;
        case 3: // CAND_NODE_ID
          return CAND_NODE_ID;
        case 4: // CAND_WEIGHT
          return CAND_WEIGHT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DOMAINID_ISSET_ID = 0;
  private static final int __CANDNODEID_ISSET_ID = 1;
  private static final int __CANDWEIGHT_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.DOMAIN_ID,_Fields.CAND_NODE_ID,_Fields.CAND_WEIGHT};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HEADER, new org.apache.thrift.meta_data.FieldMetaData("header", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AsyncMessageHeader.class)));
    tmpMap.put(_Fields.DOMAIN_ID, new org.apache.thrift.meta_data.FieldMetaData("domainId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.CAND_NODE_ID, new org.apache.thrift.meta_data.FieldMetaData("candNodeId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.CAND_WEIGHT, new org.apache.thrift.meta_data.FieldMetaData("candWeight", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LeaderCandMessage.class, metaDataMap);
  }

  public LeaderCandMessage() {
  }

  public LeaderCandMessage(
    AsyncMessageHeader header)
  {
    this();
    this.header = header;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LeaderCandMessage(LeaderCandMessage other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetHeader()) {
      this.header = new AsyncMessageHeader(other.header);
    }
    this.domainId = other.domainId;
    this.candNodeId = other.candNodeId;
    this.candWeight = other.candWeight;
  }

  public LeaderCandMessage deepCopy() {
    return new LeaderCandMessage(this);
  }

  @Override
  public void clear() {
    this.header = null;
    setDomainIdIsSet(false);
    this.domainId = 0;
    setCandNodeIdIsSet(false);
    this.candNodeId = 0;
    setCandWeightIsSet(false);
    this.candWeight = 0;
  }

  public AsyncMessageHeader getHeader() {
    return this.header;
  }

  public LeaderCandMessage setHeader(AsyncMessageHeader header) {
    this.header = header;
    return this;
  }

  public void unsetHeader() {
    this.header = null;
  }

  /** Returns true if field header is set (has been assigned a value) and false otherwise */
  public boolean isSetHeader() {
    return this.header != null;
  }

  public void setHeaderIsSet(boolean value) {
    if (!value) {
      this.header = null;
    }
  }

  public short getDomainId() {
    return this.domainId;
  }

  public LeaderCandMessage setDomainId(short domainId) {
    this.domainId = domainId;
    setDomainIdIsSet(true);
    return this;
  }

  public void unsetDomainId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DOMAINID_ISSET_ID);
  }

  /** Returns true if field domainId is set (has been assigned a value) and false otherwise */
  public boolean isSetDomainId() {
    return EncodingUtils.testBit(__isset_bitfield, __DOMAINID_ISSET_ID);
  }

  public void setDomainIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DOMAINID_ISSET_ID, value);
  }

  public short getCandNodeId() {
    return this.candNodeId;
  }

  public LeaderCandMessage setCandNodeId(short candNodeId) {
    this.candNodeId = candNodeId;
    setCandNodeIdIsSet(true);
    return this;
  }

  public void unsetCandNodeId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CANDNODEID_ISSET_ID);
  }

  /** Returns true if field candNodeId is set (has been assigned a value) and false otherwise */
  public boolean isSetCandNodeId() {
    return EncodingUtils.testBit(__isset_bitfield, __CANDNODEID_ISSET_ID);
  }

  public void setCandNodeIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CANDNODEID_ISSET_ID, value);
  }

  public int getCandWeight() {
    return this.candWeight;
  }

  public LeaderCandMessage setCandWeight(int candWeight) {
    this.candWeight = candWeight;
    setCandWeightIsSet(true);
    return this;
  }

  public void unsetCandWeight() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CANDWEIGHT_ISSET_ID);
  }

  /** Returns true if field candWeight is set (has been assigned a value) and false otherwise */
  public boolean isSetCandWeight() {
    return EncodingUtils.testBit(__isset_bitfield, __CANDWEIGHT_ISSET_ID);
  }

  public void setCandWeightIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CANDWEIGHT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HEADER:
      if (value == null) {
        unsetHeader();
      } else {
        setHeader((AsyncMessageHeader)value);
      }
      break;

    case DOMAIN_ID:
      if (value == null) {
        unsetDomainId();
      } else {
        setDomainId((Short)value);
      }
      break;

    case CAND_NODE_ID:
      if (value == null) {
        unsetCandNodeId();
      } else {
        setCandNodeId((Short)value);
      }
      break;

    case CAND_WEIGHT:
      if (value == null) {
        unsetCandWeight();
      } else {
        setCandWeight((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HEADER:
      return getHeader();

    case DOMAIN_ID:
      return Short.valueOf(getDomainId());

    case CAND_NODE_ID:
      return Short.valueOf(getCandNodeId());

    case CAND_WEIGHT:
      return Integer.valueOf(getCandWeight());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HEADER:
      return isSetHeader();
    case DOMAIN_ID:
      return isSetDomainId();
    case CAND_NODE_ID:
      return isSetCandNodeId();
    case CAND_WEIGHT:
      return isSetCandWeight();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof LeaderCandMessage)
      return this.equals((LeaderCandMessage)that);
    return false;
  }

  public boolean equals(LeaderCandMessage that) {
    if (that == null)
      return false;

    boolean this_present_header = true && this.isSetHeader();
    boolean that_present_header = true && that.isSetHeader();
    if (this_present_header || that_present_header) {
      if (!(this_present_header && that_present_header))
        return false;
      if (!this.header.equals(that.header))
        return false;
    }

    boolean this_present_domainId = true && this.isSetDomainId();
    boolean that_present_domainId = true && that.isSetDomainId();
    if (this_present_domainId || that_present_domainId) {
      if (!(this_present_domainId && that_present_domainId))
        return false;
      if (this.domainId != that.domainId)
        return false;
    }

    boolean this_present_candNodeId = true && this.isSetCandNodeId();
    boolean that_present_candNodeId = true && that.isSetCandNodeId();
    if (this_present_candNodeId || that_present_candNodeId) {
      if (!(this_present_candNodeId && that_present_candNodeId))
        return false;
      if (this.candNodeId != that.candNodeId)
        return false;
    }

    boolean this_present_candWeight = true && this.isSetCandWeight();
    boolean that_present_candWeight = true && that.isSetCandWeight();
    if (this_present_candWeight || that_present_candWeight) {
      if (!(this_present_candWeight && that_present_candWeight))
        return false;
      if (this.candWeight != that.candWeight)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(LeaderCandMessage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    LeaderCandMessage typedOther = (LeaderCandMessage)other;

    lastComparison = Boolean.valueOf(isSetHeader()).compareTo(typedOther.isSetHeader());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHeader()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.header, typedOther.header);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDomainId()).compareTo(typedOther.isSetDomainId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDomainId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.domainId, typedOther.domainId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCandNodeId()).compareTo(typedOther.isSetCandNodeId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCandNodeId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.candNodeId, typedOther.candNodeId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCandWeight()).compareTo(typedOther.isSetCandWeight());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCandWeight()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.candWeight, typedOther.candWeight);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LeaderCandMessage(");
    boolean first = true;

    sb.append("header:");
    if (this.header == null) {
      sb.append("null");
    } else {
      sb.append(this.header);
    }
    first = false;
    if (isSetDomainId()) {
      if (!first) sb.append(", ");
      sb.append("domainId:");
      sb.append(this.domainId);
      first = false;
    }
    if (isSetCandNodeId()) {
      if (!first) sb.append(", ");
      sb.append("candNodeId:");
      sb.append(this.candNodeId);
      first = false;
    }
    if (isSetCandWeight()) {
      if (!first) sb.append(", ");
      sb.append("candWeight:");
      sb.append(this.candWeight);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (header == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'header' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (header != null) {
      header.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LeaderCandMessageStandardSchemeFactory implements SchemeFactory {
    public LeaderCandMessageStandardScheme getScheme() {
      return new LeaderCandMessageStandardScheme();
    }
  }

  private static class LeaderCandMessageStandardScheme extends StandardScheme<LeaderCandMessage> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LeaderCandMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HEADER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.header = new AsyncMessageHeader();
              struct.header.read(iprot);
              struct.setHeaderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DOMAIN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.domainId = iprot.readI16();
              struct.setDomainIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CAND_NODE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.candNodeId = iprot.readI16();
              struct.setCandNodeIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CAND_WEIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.candWeight = iprot.readI32();
              struct.setCandWeightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LeaderCandMessage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.header != null) {
        oprot.writeFieldBegin(HEADER_FIELD_DESC);
        struct.header.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.isSetDomainId()) {
        oprot.writeFieldBegin(DOMAIN_ID_FIELD_DESC);
        oprot.writeI16(struct.domainId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCandNodeId()) {
        oprot.writeFieldBegin(CAND_NODE_ID_FIELD_DESC);
        oprot.writeI16(struct.candNodeId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCandWeight()) {
        oprot.writeFieldBegin(CAND_WEIGHT_FIELD_DESC);
        oprot.writeI32(struct.candWeight);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LeaderCandMessageTupleSchemeFactory implements SchemeFactory {
    public LeaderCandMessageTupleScheme getScheme() {
      return new LeaderCandMessageTupleScheme();
    }
  }

  private static class LeaderCandMessageTupleScheme extends TupleScheme<LeaderCandMessage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LeaderCandMessage struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.header.write(oprot);
      BitSet optionals = new BitSet();
      if (struct.isSetDomainId()) {
        optionals.set(0);
      }
      if (struct.isSetCandNodeId()) {
        optionals.set(1);
      }
      if (struct.isSetCandWeight()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetDomainId()) {
        oprot.writeI16(struct.domainId);
      }
      if (struct.isSetCandNodeId()) {
        oprot.writeI16(struct.candNodeId);
      }
      if (struct.isSetCandWeight()) {
        oprot.writeI32(struct.candWeight);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LeaderCandMessage struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.header = new AsyncMessageHeader();
      struct.header.read(iprot);
      struct.setHeaderIsSet(true);
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.domainId = iprot.readI16();
        struct.setDomainIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.candNodeId = iprot.readI16();
        struct.setCandNodeIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.candWeight = iprot.readI32();
        struct.setCandWeightIsSet(true);
      }
    }
  }

}

